name: memoriku_kelompok5
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  image_picker: ^0.8.6
  image_editor: ^1.0.0
  flutter_background_service: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1
  http: ^1.2.2 # Choose the version you need
  file_picker: ^8.0.0
  provider: ^6.1.2
  flutter_image_compress: ^1.1.3
  dio: ^5.3.2
  path_provider: ^2.0.11
  permission_handler: ^10.4.3
  universal_html: ^2.2.4

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_profile.png
